### ISSUE TITLE
Hello, can you share the complete video?

### ISSUE THREAD

**Issue by zhuay112** [Tuesberry/TestServer#1]
[Rookiss, [C++과 언리얼로 만드는 MMORPG 게임 개발 시리즈] Part4: 게임 서버, 인프런](https://www.inflearn.com/course/%EC%96%B8%EB%A6%AC%EC%96%BC-3d-mmorpg-4)
Hello, can you share the complete video?

**Comment by Tuesberry** [comment]
I can't share the Rookiss's lectures as it is a paid content.
You can access the lectures by paying through the following link.
[Rookiss, [C++과 언리얼로 만드는 MMORPG 게임 개발 시리즈] Part4: 게임 서버, 인프런](https://www.inflearn.com/course/%EC%96%B8%EB%A6%AC%EC%96%BC-3d-mmorpg-4)
